Update: docker compose command

diff --git a/.github/workflows/ec2deploy.yaml b/.github/workflows/ec2deploy.yaml
--- a/.github/workflows/ec2deploy.yaml
+++ b/.github/workflows/ec2deploy.yaml
@@ -103,7 +103,7 @@ jobs:
             sudo docker rm dockerdemo || true
 
             echo "Running new container..."
-           sudo docker-compose -f ~/docker-compose.yaml up -d || echo "Docker Compose failed!"
+            sudo docker-compose -f ~/docker-compose.yaml up -d || echo "Docker Compose failed!"
             sleep 5
 
             echo "Verifying running containers..."
