Added: docker docker command

diff --git a/.github/workflows/ec2deploy.yaml b/.github/workflows/ec2deploy.yaml
--- a/.github/workflows/ec2deploy.yaml
+++ b/.github/workflows/ec2deploy.yaml
@@ -33,6 +33,21 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+      - name: Ensure Docker is installed
+        run: |
+          ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-18-233-157-140.compute-1.amazonaws.com << 'EOF'
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing..."
+              sudo apt update
+              sudo apt install -y docker.io
+              sudo systemctl enable docker
+              sudo systemctl start docker
+              sudo usermod -aG docker ubuntu
+            else
+              echo "Docker is already installed."
+            fi
+          EOF
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
